version: 2

updates:
  # Update Github Actions weekly
  - package-ecosystem: 'github-actions'
    # Directory is relative so .github is the root to access /workflows
    directory: '/'
    schedule:
      # Check for updates to GitHub Actions every week
      interval: 'weekly'

  # Update npm dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'