# Used for SPAs to handle the routing internally
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Set the headers for security
[[headers]]
  for = "/*"
  [headers.values]
    SameSite = "Lax"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "base-uri 'self'; object-src 'none'; script-src 'self'; style-src 'self' fonts.googleapis.com 'unsafe-inline'; font-src fonts.gstatic.com; frame-ancestors 'none'; frame-src youtube.com www.youtube.com; manifest-src 'self'"