# Used for SPAs to handle the routing internally
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Set the headers for security
[[headers]]
  for = "/*"
  [headers.values]
    SameSite = "Lax"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    # Setting an empty value ensures that they aren't used
    Permissions-Policy = """
      geolocation=(),
      microphone=(),
      camera=(),
      fullscreen=*
    """
    Content-Security-Policy = """
      default-src 'none'; 
      connect-src 'self' api.whitelist-crypto.io; 
      object-src 'none';
      img-src 'self' data:; 
      script-src 'self' cloudfront.net *.cloudfront.net; 
      style-src 'unsafe-inline' fonts.googleapis.com cloudfront.net *.cloudfront.net; 
      font-src fonts.gstatic.com; 
      frame-ancestors 'none'; 
      frame-src youtube.com www.youtube.com;
      manifest-src 'self'
    """