name: Dependabot Pull Request Approve and Merge

on: 
  pull_request: 
    branches: 
      - main

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    name: Automerge dependabot PR
    runs-on: ubuntu-latest
    # Checking the actor will prevent your Action run failing on non-Dependabot
    # PRs but also ensures that it only does work for Dependabot PRs.
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: 'Wait for status checks'
        id: waitforstatuschecks
        uses: "WyriHaximus/github-action-wait-for-status@latest"
        with:
          ignoreActions: Automerge dependabot PR
          checkInterval: 20
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      # This first step will wait until  fail if there's no metadata and so the approval
      # will not occur
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1.1.1
        if: steps.waitforstatuschecks.outputs.status == 'success'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      # Here the PR gets approved.
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Finally, this sets the PR to allow auto-merging for patch and minor
      # updates if all checks pass
      - name: Enable auto-merge for Dependabot PRs
        if: ${{ steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major' }}
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}