name: Dependabot PR Approve and Merge

on: 
  pull_request: 
    branches: 
      - main

# permissions:
#   pull-requests: write
#   contents: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    # Checking the actor will prevent your Action run failing on non-Dependabot
    # PRs but also ensures that it only does work for Dependabot PRs.
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      # Skip duplicates and prevents workflows from running twice
      - name: Cancel Previous Runs Actions
        uses: LarchLiu/cancel_previous_runs@V1.1.0

      # Pauses the rest of the workflow, waiting for the results of other actions,
      # in this case, the build and test workflows.
      - name: Wait for status checks
        id: waitforstatuschecks
        uses: "WyriHaximus/github-action-wait-for-status@v1.4.0"
        with:
          ignoreActions: automerge
          checkInterval: 20
        env:
          GITHUB_TOKEN: "${{ secrets.AUTO_MERGE }}"

      # Fetches the metatada about the dependencies being updated. The workflow
      # will only continue if the status of the other workflows were successful,
      # otherwise, will skip the rest of the workflow and not merge
      - name: Dependabot metadata
        if: steps.waitforstatuschecks.outputs.status == 'success'
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1.1.1
        with:
          github-token: "${{ secrets.AUTO_MERGE }}"

      # Here the PR gets approved.
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      # Finally, this sets the PR to allow auto-merging for patch and minor
      # updates if all checks pass
      - name: Enable auto-merge for Dependabot PRs
        if: ${{ steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major' }}
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      # After successfully merging the PR, this updates the other open PRs
      # with the new result of the merge.
      - name: Update remaining PRs
        if: steps.merge.outputs.merge_status == 0
        uses: tzkhan/pr-update-action@v2
        with:
          repo-token: "${{ secrets.AUTO_MERGE }}"

      #   run: bash .github/workflows/pull-request-update.sh "${{ secrets.AUTO_MERGE }}" "${{ secrets.AUTO_MERGE }}"