name: Build

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

env:
  COMPILE_TEST: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Skip duplicates and prevents workflows from running twice
      - name: Cancel Previous Runs Actions
        uses: LarchLiu/cancel_previous_runs@V1.1.0
        
      - name: Checkout code
        uses: actions/checkout@master

      - name: Use NodeJS 17.4.0
        uses: actions/setup-node@master
        with:
          node-version: '17.4.0'
          cache: npm

      - run: npm install
      
      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Compile
        run: npm start