name: Deploy to Production

on:
  push:
    branches: test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:       
      - name: Checkout code
        uses: actions/checkout@master

      - name: Use NodeJS 17.4.0
        uses: actions/setup-node@master
        with:
          node-version: '17.4.0'
          cache: npm

      - name: Install dependencies
        run: npm install
      
      # - name: Test
      #   run: npm test

      - name: Build
        run: npm run build

      # - name: Compile
      #   run: npm start
      #   env:
      #     COMPILE_TEST: true

      - name: deploy build
        run: netlify deploy --prod --dir build --message "$MESSAGE"
        env:
          NETLIFY_SITE_ID: a115dba5-ccae-4bed-9f8d-938685aadb67
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          MESSAGE: ${{ github.event.head_commit.message }}

