name: Publish 

#
# Currently disabled in Github Actions on the repository
#

# Only publishes the main branch when pushed upstream
on:
  push:
    branches: 
      - main

  # Allows this workflow to be ran manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Use NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - run: npm install 
      - run: npm run build

      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --prod --message "${{ github.event.head_commit.message }}"
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}