name: Test

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches: 
      - main

  workflow_dispatch:

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      # Skip duplicates and prevents workflows from running twice
      - name: Cancel Previous Runs Actions
        uses: LarchLiu/cancel_previous_runs@V1.1.0
        
      - name: Checkout code
        uses: actions/checkout@master

      - name: Use NodeJS 17.4.0
        uses: actions/setup-node@master
        with:
          node-version: '17.4.0'
          cache: npm

      - run: npm install
      - run: npm run test