name: Test

# Run the test workflow when all branches besides main is pushed upstream
# and on pull requests on the main branch
on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches: 
      - main

  # Allows this workflow to be ran manually from the Actions tab
  workflow_dispatch:

jobs:
  test: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
      # Skip duplicates and prevents workflows from running twice
      - name: Cancel Previous Runs Actions
        uses: LarchLiu/cancel_previous_runs@V1.1.0
        
      - name: Checkout code
        uses: actions/checkout@master

      - name: Use NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - run: npm install
      - run: npm run test